export const types = {
    GET_RECOMMENDEDMOVIES: 'GET_RECOMMENDEDMOVIES',
    GET_CONTINUEWATCHING: 'GET_CONTINUEWATCHING',
    GET_THEME_SUCCESS: "GET_THEME_SUCCESS",
    PAGE_CONTENT: 'PAGE_CONTENT'
}