export const signUpConstants = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
    RESET_SIGNUP: "RESET_SIGNUP",
    RESET_SIGNUP_AFTER_ACTIVATION: "RESET_SIGNUP_AFTER_ACTIVATION"
};
